### ISSUE TITLE
"resources/Presets/OpenCL" missing on install

### ISSUE THREAD

**Issue by Juanlu001** [sanguinariojoe/aquagpusph#1]
I failed to install AQUAgpusph on a virtualized Linux Mint 17. Step `make install` fails, see log:

https://gist.github.com/Juanlu001/a38006abd31a71a25871

**Comment by sanguinariojoe** [comment]
Thanks Juanlu!

The last 2 commits should fix the installation process, however I have not checked yet that the installed version is working properly.

While the version 2.0 is not officially released it is strongly recommended don't installing it. Of course you can still using the tool:

>  cmake -DAQUAGPUSPH_3D=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr .
> make
> cd examples/spheric_testcase10_waveimpact/
> ./run.sh --run

**Comment by Juanlu001** [comment]
Great! Problem fixed. I am getting OpenCL errors now but those deserve a different issue. Thanks!
