### ISSUE TITLE
Building problems

### ISSUE THREAD

**Issue by Juanlu001** [sanguinariojoe/aquagpusph#2]
I am having problems while trying to compile the library when the dependencies are not installed top-level prefixes.

So far, I already had to patch cMake/FindNumpy.cmake because I was getting errors in the vein of `numpy/ndarraytypes.h not found`.

```
--- cMake/FindNumpy.cmake
+++ cMake/FindNumpy.cmake
@@ -28,6 +28,8 @@ FIND_PATH(NUMPY_INCLUDE_DIRS
     ${NUMPY_INCLUDE_DIR}
 )
 
+INCLUDE_DIRECTORIES(${NUMPY_INCLUDE_DIR} ${NUMPY_INCLUDE_DIRS})
+
 # Lets find the numpy module
 EXECUTE_PROCESS(
     COMMAND ${PYTHON_EXECUTABLE} -c "import numpy, os; print os.path.dirname(numpy.__file__)"
```

I have been unable to remove all linking errors though. I disabled VTK temporarily so I could get clearer error messages, but basically the libraries are not being located correctly, even if the paths are correct. I am not an expert on CMake so I cannot dig any further.

This is my build command:

```
cmake \
    -DAQUAGPUSPH_3D=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DOPENCL_ROOT_DIR=/opt/intel/opencl-sdk \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_PREFIX_PATH=$PREFIX \
    -DAQUAGPUSPH_USE_VTK:BOOL=OFF \
    .
make
make install
```

Relevant error messages:

```
[ 93%] Building CXX object src/CMakeFiles/AQUAgpusphClient.dir/Variable.cpp.o
[ 96%] Building CXX object src/CMakeFiles/AQUAgpusphClient.dir/Tokenizer/Tokenizer.cpp.o
Linking CXX shared library ../lib/libAQUAgpusphClient.so
[ 96%] Built target AQUAgpusphClient
Scanning dependencies of target AQUAgpusph
[100%] Building CXX object src/CMakeFiles/AQUAgpusph.dir/main.cpp.o
Linking CXX executable ../bin/AQUAgpusph
/usr/bin/ld: warning: libLLVM-3.3.so, needed by /home/juanlu/.miniconda3/envs/_build/lib/../lib/libclang.so, not found (try using -rpath or -rpath-link)
/home/juanlu/.miniconda3/envs/_build/lib/../lib/libclang.so: undefined reference to `llvm::MemoryBuffer::getFile(llvm::StringRef, llvm::OwningPtr<llvm::MemoryBuffer>&, long, bool)'
[...Lots more...]
```

And contents of src/CMakeFiles/AQUAgpusph.dir/link.txt:

```
/usr/bin/c++    -w -O3 -DNDEBUG    CMakeFiles/AQUAgpusph.dir/main.cpp.o  -o ../bin/AQUAgpusph -rdynamic ../lib/libAQUAgpusphClient.so ../lib/libAQUAgpusphServer.so /opt/intel/opencl-sdk/lib64/libOpenCL.so -lpython3.4m -lxerces-c -lcurses -lmatheval -lclang -lcurses -Wl,-rpath,/home/juanlu/.miniconda3/conda-bld/work/lib:/opt/intel/opencl-sdk/lib64: 
```

**Actually** I edited this last file "on the fly" (pausing the compilation after it was generated...) to add the actual path of libLLVM:

` /home/juanlu/.miniconda3/envs/_build/lib/libLLVM-3.3.so`

and the compilation resumed without errors, so there is some problem in the generation of the paths.

**Comment by sanguinariojoe** [comment]
Thanks Juanlu!

Numpy:
`numpy/ndarraytypes.h not found.`
What file is compiling when you got this error? With your patch is that your are adding the flags to whole project, which is an undesirable overhead

---

LLVM:
Is it a distro related problem? Ussually linking with clang does not require to link with llvm as well due to llvm is statically linked.

Anyway, I uploaded a patch which should fix the problem

**Comment by Juanlu001** [comment]
Latest commits fixed many problems, and for the rest I definitely have to check the linker. Closing this!
