### ISSUE TITLE
particles distribution file for benchmark 10

### ISSUE THREAD

**Issue by VicenteR** [sanguinariojoe/aquagpusph#6]
The idea is just to run benchmark 10 again with other particles distribution file. For creating this file, "tanque.dat", I have used an Aquagpusph preprocessing tool: 
`./AQUAgpusph-loadGiD --level 0.35 --deltar 0.007 -o tanque.dat  cab_conf0_nivel1_escala_modelo.msh`

Previously the output of this generator was modified as follows:

```
for p in particles:
        string = """%g %g %g %g %g %g 0.0 0.0 0.0 0.0 0.0 0.0 %g 0.0 %g %d\n""" % (p[0][0], p[0][1], p[0][2],
                                                                                   p[1][0], p[1][1], p[1][2],
                                                                                   p[3],
                                                                                   p[2],
                                                                                   1)

```

Fluids.xml was customiced as follows: `<Load format="FastASCII" file="tanque.dat" fields="r, normal, u, dudt, rho, drhodt, m, imove" />
`
All references about sensors were deleted, because AQUA showed some errors.

I obtenied following error too: 
```
INFO (ASCII::load): Loading particles from ASCII file "tanque.dat"
ERROR (ASCII::load): Expected 20 fields, but a line contains 16 ones.
        error found in the line 33.
        "-0.1225,-0.316484,0.314077,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1001.56,0.0,0.000322049,1".
```

The last line is a particle/vertex of tanque.dat, with 16 variables format.

Then I rewrote the generator AQUAgpusph-loadGiD with the same string of create.py in benchmark 10.
```

for p in particles:
        string = ("{} {} {} 0.0, " * 4 + "{}, {}, {}, {}\n").format(	p[0][0], p[0][1], p[0][2],
								        p[1][0], p[1][1], p[1][2],
								        0.0, 0.0, 0.0,
								        0.0, 0.0, 0.0,
								        p[3],
								        0.0,
								        p[2],
								        1)
        f.write(string)
    	for v in vertexes:
 	string = ("{} {} {} 0.0, " * 4 + "{}, {}, {}, {}\n").format(	v[0][0], v[0][1], v[0][2],
								        v[1][0], v[1][1], v[1][2],
								        0.0, 0.0, 0.0,
								        0.0, 0.0, 0.0,
								        v[3],
								        0.0,
								        v[2],
								        -1)        

```

With 20 variables particles distribution file, aquagpusph crashes when it starts to compute, and it shows during two seconds:

```
list index out of range
:
IndexError
if motion_r[motion_iset] is NOne:
File "...../OpenCL/Motions/State.py", line 50, in main
Traceback (most recent call last):
(Python::_execute: main() function execution failed.
```

I have done something wrong, but I don't know what. Any idea?

Thank you very much for your time.

**Comment by sanguinariojoe** [comment]
That's because you are trying to load fields not saved by AQUAgpusph-loadGiD. Such tool was not saving dudt or drhodt.

In fact, this is a bug of the current version of AQUAgpusph, since right now it is requiring to manually initialize both, dudt and drhodt.

I conveniently updated the tools to work properly:
https://github.com/sanguinariojoe/aquagpusph/commit/d5fafe0bf4869a47ffe7dc55b04315ab08a0311c

Check it and let me know if something fails again

Thanks!
Pepe

**Comment by VicenteR** [comment]
I used another output syntax. I added 4 zeros, because benchmark 10 doesn't run. 
`template = "{} {} {} 0.0, " * 2 + "0.0 0.0 0.0 0.0, " * 2 + "{}, " + "0.0, " + "{}, " + "{}\n"`

With this format, I could simulated benchmarkt 10 two times, the second one with forces too.

After these two simulations, I have a endless list of errors when I run "loadGiD", like:

```
* ImportError: No module named 'numpy'

* ImportError: No module named 'vec'

* ImportError: No module named 'aquagpusph_preprocessing'

* File "./AQUAgpusph-loadGiD", line 44
    header = """#############################################################
         ^
    SyntaxError: invalid syntax

* File "./AQUAgpusph-loadGiD", line 88
    parser = ArgumentParser(description = description ,
                                                      ^
    TabError: inconsistent use of tabs and spaces in indentation

* File "./AQUAgpusph-loadGiD", line 166
    
                  ^
    SyntaxError: unexpected EOF while parsing
```

And finally, I solved all these errors one way or another, now when loadGiD is launched, it doesn't do anything.

I know this is probably a super basic errors, but I'm still learning... Thanks

**Comment by sanguinariojoe** [comment]
Op! You are right! a fourth component is required at vector variables. Thanks:

7dc60f735e3d4b830dd6aa39243a144d47f5db66

Regarding the errors... That's strange... Could you send me the mesh file? (It's a text file, so you may just copy/paste it)

**Comment by VicenteR** [comment]
I could solve the different errors. And I could run with some meshes, but in all cases the tank ends empty, all particles fell.

For example, I used the following mesh in the benchmark 10, generating tanque04v.dat (./AQUAgpusph-loadGiD --level 0.412 --deltar 0.0035 -o tanque04v.dat tanque2004v.msh), and it's only modified the number of particles and the name of the ".dat" file in "fluids.xml".

THX!!!!!

`MESH    dimension 3 ElemType Quadrilateral  Nnode 4
Coordinates
    1          -0.07         -0.315          0.382
    2          -0.07         -0.315          0.445
    3   9.71445e-017         -0.315          0.382
    4          -0.07       -0.23625          0.382
    5   1.04083e-016         -0.315          0.445
    6   1.04083e-016       -0.23625          0.382
    7          -0.07      -0.228679        0.44453
    8          -0.07         -0.315          0.508
    9           0.07         -0.315          0.382
   10   1.04083e-016         -0.315          0.508
   11           0.07         -0.315          0.445
   12          -0.07      -0.226395       0.507383
   13          -0.07        -0.1575          0.382
   14           0.07       -0.23625          0.382
   15   1.04083e-016        -0.1575          0.382
   16           0.07      -0.230556       0.445336
   17          -0.07       -0.13707       0.443738
   18           0.07         -0.315          0.508
   19          -0.07         -0.315          0.571
   20   1.04083e-016         -0.315          0.571
   21          -0.07      -0.228787        0.57046
   22           0.07      -0.227695       0.508549
   23           0.07        -0.1575          0.382
   24          -0.07      -0.132721        0.50652
   25           0.07      -0.143277       0.445796
   26           0.07         -0.315          0.571
   27          -0.07       -0.07875          0.382
   28   1.04083e-016       -0.07875          0.382
   29           0.07      -0.228968       0.571465
   30          -0.07         -0.315          0.634
   31          -0.07      -0.145082       0.570348
   32          -0.07     -0.0616845       0.444473
   33   1.11022e-016         -0.315          0.634
   34           0.07      -0.132129       0.509542
   35          -0.07       -0.23625          0.634
   36   1.04083e-016       -0.23625          0.634
   37           0.07       -0.07875          0.382
   38           0.07         -0.315          0.634
   39          -0.07     -0.0518239        0.50714
   40           0.07      -0.136927       0.572309
   41          -0.07        -0.1575          0.634
   42           0.07       -0.23625          0.634
   43           0.07     -0.0560764       0.445987
   44   1.11022e-016        -0.1575          0.634
   45          -0.07              0          0.382
   46          -0.07     -0.0613186       0.570413
   47   1.04083e-016              0          0.382
   48           0.07     -0.0512053       0.508994
   49           0.07        -0.1575          0.634
   50          -0.07      0.0137279       0.445064
   51           0.07              0          0.382
   52          -0.07       -0.07875          0.634
   53           0.07     -0.0609491       0.571682
   54   1.04083e-016       -0.07875          0.634
   55          -0.07      0.0232327       0.508199
   56           0.07      0.0196672       0.444936
   57           0.07       -0.07875          0.634
   58          -0.07      0.0175902       0.571055
   59           0.07      0.0249564       0.508038
   60          -0.07        0.07875          0.382
   61   1.04083e-016        0.07875          0.382
   62          -0.07              0          0.634
   63           0.07      0.0138607       0.571127
   64          -0.07      0.0886411       0.445386
   65   1.04083e-016              0          0.634
   66           0.07        0.07875          0.382
   67           0.07              0          0.634
   68          -0.07      0.0965789        0.50888
   69           0.07        0.09726       0.443444
   70          -0.07      0.0948029       0.571923
   71           0.07      0.0980111       0.507176
   72          -0.07        0.07875          0.634
   73           0.07      0.0914354       0.570789
   74          -0.07         0.1575          0.382
   75   1.04083e-016        0.07875          0.634
   76   1.11022e-016         0.1575          0.382
   77          -0.07       0.165508         0.4456
   78           0.07        0.07875          0.634
   79           0.07         0.1575          0.382
   80          -0.07       0.168832       0.509037
   81           0.07       0.171674       0.443087
   82           0.07       0.170344       0.506824
   83          -0.07        0.17106       0.572755
   84           0.07       0.165894       0.570556
   85          -0.07         0.1575          0.634
   86   1.11022e-016         0.1575          0.634
   87          -0.07        0.23625          0.382
   88           0.07         0.1575          0.634
   89          -0.07        0.23625          0.445
   90   1.04083e-016        0.23625          0.382
   91           0.07        0.23625          0.382
   92          -0.07       0.242184       0.508915
   93           0.07       0.247748       0.442531
   94           0.07       0.242336       0.507089
   95          -0.07       0.247748       0.573469
   96           0.07        0.23625          0.571
   97          -0.07        0.23625          0.634
   98   1.04083e-016        0.23625          0.634
   99           0.07        0.23625          0.634
  100          -0.07          0.315          0.382
  101          -0.07          0.315          0.445
  102   9.71445e-017          0.315          0.382
  103   1.04083e-016          0.315          0.445
  104          -0.07          0.315          0.508
  105           0.07          0.315          0.382
  106   1.04083e-016          0.315          0.508
  107           0.07          0.315          0.445
  108           0.07          0.315          0.508
  109          -0.07          0.315          0.571
  110   1.04083e-016          0.315          0.571
  111           0.07          0.315          0.571
  112          -0.07          0.315          0.634
  113   1.11022e-016          0.315          0.634
  114           0.07          0.315          0.634
end coordinates

Elements
    1         21      35      30      19
    2         21      19       8      12
    3         21      12      24      31
    4         21      31      41      35
    5          7       2       1       4
    6          7       4      13      17
    7          7      17      24      12
    8          7      12       8       2
    9         89      87     100     101
   10         89     101     104      92
   11         89      92      80      77
   12         89      77      74      87
   13         95     109     112      97
   14         95      97      85      83
   15         95      83      80      92
   16         95      92     104     109
   17         32      17      13      27
   18         32      27      45      50
   19         32      50      55      39
   20         32      39      24      17
   21         64      50      45      60
   22         64      60      74      77
   23         64      77      80      68
   24         64      68      55      50
   25         46      39      55      58
   26         46      58      62      52
   27         46      52      41      31
   28         46      31      24      39
   29         70      72      62      58
   30         70      58      55      68
   31         70      68      80      83
   32         70      83      85      72
   33         93      91     105     107
   34         93     107     108      94
   35         93      94      82      81
   36         93      81      79      91
   37         96     111     114      99
   38         96      99      88      84
   39         96      84      82      94
   40         96      94     108     111
   41         29      42      38      26
   42         29      26      18      22
   43         29      22      34      40
   44         29      40      49      42
   45         16      11       9      14
   46         16      14      23      25
   47         16      25      34      22
   48         16      22      18      11
   49         53      57      49      40
   50         53      40      34      48
   51         53      48      59      63
   52         53      63      67      57
   53         43      56      59      48
   54         43      48      34      25
   55         43      25      23      37
   56         43      37      51      56
   57         73      78      67      63
   58         73      63      59      71
   59         73      71      82      84
   60         73      84      88      78
   61         69      56      51      66
   62         69      66      79      81
   63         69      81      82      71
   64         69      71      59      56
   65          6      14       9       3
   66          6       3       1       4
   67          6       4      13      15
   68          6      15      23      14
   69         90      87     100     102
   70         90     102     105      91
   71         90      91      79      76
   72         90      76      74      87
   73         61      60      74      76
   74         61      76      79      66
   75         61      66      51      47
   76         61      47      45      60
   77         28      27      45      47
   78         28      47      51      37
   79         28      37      23      15
   80         28      15      13      27
   81        110     106     108     111
   82        110     111     114     113
   83        110     113     112     109
   84        110     109     104     106
   85        103     107     108     106
   86        103     106     104     101
   87        103     101     100     102
   88        103     102     105     107
   89         36      33      30      35
   90         36      35      41      44
   91         36      44      49      42
   92         36      42      38      33
   93         98     113     114      99
   94         98      99      88      86
   95         98      86      85      97
   96         98      97     112     113
   97         54      44      41      52
   98         54      52      62      65
   99         54      65      67      57
  100         54      57      49      44
  101         75      65      62      72
  102         75      72      85      86
  103         75      86      88      78
  104         75      78      67      65
  105         20      10      18      26
  106         20      26      38      33
  107         20      33      30      19
  108         20      19       8      10
  109          5      11      18      10
  110          5      10       8       2
  111          5       2       1       3
  112          5       3       9      11
end elements
`

**Comment by sanguinariojoe** [comment]
OK! I got it! The problem are the normals... AQUAgpusph 1.4 was unaware of the normal orientation. However, right now the normals matter!

Theoretically, the normals can be extracted from the nodes, so I should investigate a bit

**Comment by sanguinariojoe** [comment]
I don't know if your mesh normals are wrong, or just simply GiD is not properly exporting them, but from the information of the nodes is not possible to consistently compute the normals orientation.

Therefore, I implemented an option to recompute the normals after loading the mesh, which is enabled by default. If you want to disable it just add the option --no-recompute-normals

**Comment by VicenteR** [comment]
After some tests in two PCs with new loadGiD files, I have had the same problem. All particles fell out of the tank.

I have could to read that normal vectors in .dat file have a ilogical value like -0.0. I replaced all these for 0.0, but the result was the same, all particles fell.

`0.07 -0.1506219875 0.535934525962 0.0, 1.0 -0.0 0.0 0.0, 0.0 0.0 0.0 0.0, 0.0 0.0 0.0 0.0, 1000.0, 0.0, 2.27609526471e-05, -3`

**Comment by sanguinariojoe** [comment]
I tested your mesh (4 comments above) in the 3.0 branch, and after 5 seconds of simulation not even a single particle has abandoned the tank.

Please, check if there is some inconsistent data in the files Fluids.xml and SPH.xml, like dr, cs (sound speed), gamma...

I executed the following command:

`./aquagpusph.cmake/tools/aquagpusph_preprocessing/AQUAgpusph-loadGiD --level 0.412 --deltar 0.0035 --refd 998.0 --gamma 1.0 -o tanque04v.dat --recompute_normals tanque2004v.msh`

And used the following XML files:

```
<?xml version="1.0" ?>

<sphInput>
    <ParticlesSet n="114370">
        <Scalar name="refd" value="998.0" />
        <Scalar name="visc_dyn" value="1.5076178831" />
        <Scalar name="delta" value="0.0" />
        <Load format="FastASCII" file="tanque04v.dat" fields="r, normal, u, dudt, rho, drhodt, m, imove" />
        <Save format="VTK" file="output" fields="r, normal, u, dudt, rho, drhodt, m, p, imove" />
    </ParticlesSet>
</sphInput>
```

```
<?xml version="1.0" ?>

<sphInput>
    <Variables>
        <Variable name="g" type="vec" value="0.0, 0.0, -9.81, 0.0" />
        <Variable name="dr" type="float" value="0.0035" />
        <Variable name="hfac" type="float" value="3.0" />
        <Variable name="h" type="float" value="hfac * dr" />
        <Variable name="cs" type="float" value="15.0" />
        <Variable name="courant" type="float" value="0.25" />
        <Variable name="domain_min" type="vec" value="-0.08, -0.748601005893306, -0.4494617751878781, 0.0" />
        <Variable name="domain_max" type="vec" value="0.08, 0.748601005893306, 0.748601005893306, 0.0" />
    </Variables>
</sphInput>
```

- - -

P.S. Don't worry about -0.0 values. In some contexts signed zeroes are allowed.

**Comment by VicenteR** [comment]
I could run some tests, and no problems. But I needed to add the "gamma" variable in fluid.xml file.

Thank you very much for your help.
