### ISSUE TITLE
AQUAgpusph-load  future-warnings

### ISSUE THREAD

**Issue by VicenteR** [sanguinariojoe/aquagpusph#7]
When "AQUAgpusph(3.0)-load"  was executed, these following warnings could be read.

> ./AQUAgpusph-loadGiD --level 0.412 --deltar 0.0047 --refd 998.0 --sound-speed 50.0 --recompute_normals -o tanque030047.dat tanque2004v.msh
> Loading mesh...
> 	Reading points...
> 		Found 114 points
> 	Reading elements...
> 		Found 112 faces
> OK
> /home/chente/aquagpusph-3.0/tools/aquagpusph_preprocessing/generator/fluid.py:247: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
>   if point != None:
> Changing normal orientation of the face 0
> Changing normal orientation of the face 1
> /home/chente/aquagpusph-3.0/tools/aquagpusph_preprocessing/generator/fluid.py:244: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
>   if point != None:
> Changing normal orientation of the face 2 ..... 103
> Creating vertexes over the solid surface...
> 0%......100%...
> OK
> Creating fluid particles inside the solid...
> 0%.../home/chente/aquagpusph-3.0/tools/aquagpusph_preprocessing/generator/fluid.py:389: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
>   if point == None:
> ...100%...
> OK
> Writing output...
> OK
> 51506 particles have been generated, set it in your fluid configuration.

Nevertheless, "tanque030047.dat" worked correctly.
Thx!!!

**Comment by sanguinariojoe** [comment]
Fixed here:
https://github.com/sanguinariojoe/aquagpusph/commit/0172b6a483b302bcaa96f4fda4581fa0740dcb7c

I integrated the changes in 3.0 and 3 branches as well

Thank you!
Pepe
