### ISSUE TITLE
error NO_LOCAL_MEM in MLS.cl 

### ISSUE THREAD

**Issue by VicenteR** [sanguinariojoe/aquagpusph#8]
With Nvidia (920M) graphic card I had Local Memory errors. After including NoLocalMem file in Main.xml, AQUAgpusph-3.0 showed an error in MLS.cl.

MLS.cl was modified with this 3 lines:

```
> /** @file
>  * @brief MLS kernel transformation matrix computation
>  */
> 
+ > #if defined(LOCAL_MEM_SIZE) && defined(NO_LOCAL_MEM)
+ >    #error NO_LOCAL_MEM has been set.
+ > #endif
> 
> #ifndef HAVE_3D
>     #include "../types/2D.h"
>     #include "../KernelFunctions/Wendland2D.hcl"
> #else
>     #include "../types/3D.h"
>     #include "../KernelFunctions/Wendland3D.hcl"
> #endif
```
Finally, AQUAgpusph can run without troubles.

AQUAgpusph hasn't had these local memory errors with a ATI graphic card (HD7970).

**Comment by sanguinariojoe** [comment]
Absolutely! Fixed here:
https://github.com/sanguinariojoe/aquagpusph/commit/ef5459938757139be9c67ee7e1cc4c159eb427b7

Thank you!
Pepe
